### ISSUE TITLE
Use XML library instead of or in addition to Regular Expressions

### ISSUE THREAD

**Issue by oxr463** [neverrend/XMLChecker#7]
See: https://github.com/tiran/defusedxml

**Comment by neverrend** [comment]
Ok. I will make a branch and get this started.

**Comment by oxr463** [comment]
I think it would just make working with the code much easier.

**Comment by neverrend** [comment]
See Branch: https://github.com/neverrend/XMLChecker/tree/xmlparser_feature

**Comment by neverrend** [comment]
TODO: 

* Need to add <checklistflaw></checklistflaw> remover
* Need to add code block counting & comparison against the counts
* Need to figure out an output the will be straight forward/easy to understand
* Count Step#s to ensure no mis-numbering are getting through
* More to come...
